In [1]:
import numpy as np

In [2]:
    routes = [
        [[1, 2, 0, 0], # [[1, 2], [],     [4, 3, 2], []],
         [0, 0, 0, 0],
         [4, 3, 2, 1],
         [0, 0, 0, 0]],
        [[0, 0, 0, 0], # [[],     [3, 4], [],        [1, 2]]
         [3, 4, 0, 0],
         [0, 0, 0, 0],
         [1, 2, 0, 0]]
    ]
routes = np.array(routes)

In [3]:
routes

array([[[1, 2, 0, 0],
        [0, 0, 0, 0],
        [4, 3, 2, 1],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [3, 4, 0, 0],
        [0, 0, 0, 0],
        [1, 2, 0, 0]]])

In [4]:
zz = np.zeros_like(routes[:,:,0:1])

In [5]:
zz

array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]]])

In [6]:
routes[0]

array([[1, 2, 0, 0],
       [0, 0, 0, 0],
       [4, 3, 2, 1],
       [0, 0, 0, 0]])

In [7]:
routes[0, :, :-1]

array([[1, 2, 0],
       [0, 0, 0],
       [4, 3, 2],
       [0, 0, 0]])

## All vessels

In [18]:
zz[:, :, 0:1]

array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]]])

Zero (depot) padded routes

In [19]:
a = np.concatenate((routes, zz), axis=2)
a

array([[[1, 2, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [4, 3, 2, 1, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [3, 4, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 2, 0, 0, 0]]])

In [20]:
b = np.concatenate((zz[:, :, 0:1], routes), axis=2)
b

array([[[0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 4, 3, 2, 1],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 3, 4, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 2, 0, 0]]])

In [21]:
distances = np.array([
    [0,1,2,3,4],
    [0,0,5,6,4],
    [0,0,0,7,4],
    [0,0,0,0,4],
    [0,0,0,0,0]]
            )
distances = distances + distances.T
distances

array([[0, 1, 2, 3, 4],
       [1, 0, 5, 6, 4],
       [2, 5, 0, 7, 4],
       [3, 6, 7, 0, 4],
       [4, 4, 4, 4, 0]])

In [22]:
distances[a, b]

array([[[1, 5, 2, 0, 0],
        [0, 0, 0, 0, 0],
        [4, 4, 7, 5, 1],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [3, 4, 4, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 5, 2, 0, 0]]])

Get total sailing distance for each vessel

In [23]:
total_sailing_distance = np.sum(distances[a,b], axis=(2,1))
total_sailing_distance

array([29, 19])

In [35]:
                            weekly_charter_costs=np.array((100000.0,
                                                           150000.0))
                            sailing_costs=np.array((1000, 1200))

In [36]:
total_sailing_distance

array([29, 19])

In [37]:
sailing_costs

array([1000, 1200])

In [38]:
np.dot(total_sailing_distance, sailing_costs)

51800

In [40]:
weekly_charter_costs

array([100000., 150000.])

In [43]:
np.sum(weekly_charter_costs) + np.dot(total_sailing_distance, sailing_costs)

301800.0

### Succsess!

## Sum cost

In [ ]:
np.dot(total_sailing_distance, np.array((1,0)))