In [1]:
import numpy as np

In [86]:
    routes = [
        [[1, 2, 0, 0], # [[1, 2], [],     [4, 3, 2], []],
         [0, 0, 0, 0],
         [4, 3, 2, 1],
         [0, 0, 0, 0]],
        [[0, 0, 0, 0], # [[],     [3, 4], [],        [1, 2]]
         [3, 4, 0, 0],
         [0, 0, 0, 0],
         [1, 2, 0, 0]]
    ]
routes = np.array(routes)

In [87]:
routes

array([[[1, 2, 0, 0],
        [0, 0, 0, 0],
        [4, 3, 2, 1],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [3, 4, 0, 0],
        [0, 0, 0, 0],
        [1, 2, 0, 0]]])

In [140]:
zz = np.zeros_like(routes[:,:,0:1])

In [141]:
zz

array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]]])

In [89]:
routes[0]

array([[1, 2, 0, 0],
       [0, 0, 0, 0],
       [4, 3, 2, 1],
       [0, 0, 0, 0]])

In [90]:
routes[0, :, :-1]

array([[1, 2, 0],
       [0, 0, 0],
       [4, 3, 2],
       [0, 0, 0]])

## One vessel

In [142]:
a = np.concatenate((routes[0], zz), axis=1)
a

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [104]:
b = np.concatenate((zz[0, :, 0:1], routes[0]), axis=1)
b

array([[0, 1, 2, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 4, 3, 2, 1],
       [0, 0, 0, 0, 0]])

In [105]:
distances = np.array([
    [0,1,2,3,4],
    [0,0,5,6,4],
    [0,0,0,7,4],
    [0,0,0,0,4],
    [0,0,0,0,0]]
            )
distances = distances + distances.T
distances

array([[0, 1, 2, 3, 4],
       [1, 0, 5, 6, 4],
       [2, 5, 0, 7, 4],
       [3, 6, 7, 0, 4],
       [4, 4, 4, 4, 0]])

In [108]:
distances[a, b]

array([[1, 5, 2, 0, 0],
       [0, 0, 0, 0, 0],
       [4, 4, 7, 5, 1],
       [0, 0, 0, 0, 0]])

In [109]:
np.sum(distances[a,b])

29

## All vessels

In [111]:
zz[:, :, 0:1]

array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]]])

Zero (depot) padded routes

In [143]:
a = np.concatenate((routes, zz), axis=2)
a

array([[[1, 2, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [4, 3, 2, 1, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [3, 4, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 2, 0, 0, 0]]])

In [113]:
b = np.concatenate((zz[:, :, 0:1], routes), axis=2)
b

array([[[0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 4, 3, 2, 1],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 3, 4, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 1, 2, 0, 0]]])

In [114]:
distances = np.array([
    [0,1,2,3,4],
    [0,0,5,6,4],
    [0,0,0,7,4],
    [0,0,0,0,4],
    [0,0,0,0,0]]
            )
distances = distances + distances.T
distances

array([[0, 1, 2, 3, 4],
       [1, 0, 5, 6, 4],
       [2, 5, 0, 7, 4],
       [3, 6, 7, 0, 4],
       [4, 4, 4, 4, 0]])

In [115]:
distances[a, b]

array([[[1, 5, 2, 0, 0],
        [0, 0, 0, 0, 0],
        [4, 4, 7, 5, 1],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [3, 4, 4, 0, 0],
        [0, 0, 0, 0, 0],
        [1, 5, 2, 0, 0]]])

Get total sailing distance for each vessel

In [144]:
total_sailing_distance = np.sum(distances[a,b], axis=(2,1))
total_sailing_distance

array([29, 19])

### Succsess!

## Sum cost

In [147]:
np.dot(total_sailing_distance, np.array((1,0)))

29