In [1]:
import numpy as np
from psvpp_solver.utils import generate_visits, generate_departures_from_visits

In [2]:
visits = generate_visits(n_installations = 4,
                    n_days_in_period=7,
                    required_services=np.array([2, 3, 2, 2], dtype=np.int8),
                    max_vessels_prepared=2)
visits*1

array([[1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 1]])

In [4]:
departures = generate_departures_from_visits(visits=visits,
                                    n_vessels=2,
                                    n_installations=4,
                                    n_days_in_period=7)
departures*1

array([[0, 1, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 1]])

In [7]:
n_days_in_period = 7

In [28]:
    routes = np.zeros(shape=(len(departures), n_days_in_period, len(visits)),
                      dtype=np.int8)
routes

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int8)

In [25]:
visits*1

array([[1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 1]])

In [10]:
np.where(visits)

(array([0, 0, 1, 1, 1, 2, 2, 3, 3]), array([0, 4, 1, 4, 6, 2, 6, 3, 6]))

In [22]:
installation_visit, day_visit = np.where(visits)

In [11]:
departures*1

array([[0, 1, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 1]])

In [ ]:
departures

In [19]:
np.where(departures)

(array([0, 0, 1, 1, 1, 1]), array([1, 2, 0, 3, 4, 6]))

In [23]:
which_vessel, day_departures = np.where(departures)

In [132]:
visits[:, day_departures].T*1

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1]])

In [133]:
a, b = np.where(visits[:, day_departures].T)
b=b+1
a, b

(array([0, 1, 2, 3, 4, 4, 5, 5, 5]), array([2, 3, 1, 4, 1, 2, 2, 3, 4]))

In [119]:
uq, counts = np.unique(a, return_counts=True)
uq, counts

(array([0, 1, 2, 3, 4, 5]), array([1, 1, 1, 1, 2, 3]))

In [134]:
from itertools import chain

installation_order_index = np.fromiter(chain.from_iterable(np.arange(x) for x in counts), dtype=np.int8)
installation_order_index

In [136]:
routes[which_vessel[a], day_departures[a], installation_order_index] = b
routes

array([[[0, 0, 0, 0],
        [2, 0, 0, 0],
        [3, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[1, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [4, 0, 0, 0],
        [1, 2, 0, 0],
        [0, 0, 0, 0],
        [2, 3, 4, 0]]], dtype=int8)

In [51]:
which_vessel[a]

array([0, 0, 1, 1, 1, 1, 1, 1, 1])

In [52]:
day_departures[a]

array([1, 2, 0, 3, 4, 4, 6, 6, 6])

In [48]:
xx = (visits[:, day_departures].T*1 * np.arange(1, len(visits)+1)).T
xx

array([[0, 0, 1, 0, 1, 0],
       [2, 0, 0, 0, 2, 2],
       [0, 3, 0, 0, 0, 3],
       [0, 0, 0, 4, 0, 4]])

In [ ]:
vessel_installation_visits

In [18]:
routes[, day_visit, np.arange(visits)] = 1

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (6,) (6,) (9,) 