In [1]:
%%time

import numpy as np

from psvpp_solver.utils import generate_visits

visits = generate_visits(n_installations = 3,
                    n_days= 7,
                    required_services=np.array([1, 2, 3], dtype=np.int8),
                    )
print(visits*1)

[[0 0 1 0 0 0 0]
 [0 0 1 0 0 1 0]
 [1 0 1 0 0 1 0]]
CPU times: user 214 ms, sys: 143 ms, total: 357 ms
Wall time: 147 ms


In [2]:
%%time
# Test generate_departures_from_visits

from psvpp_solver.utils import generate_departures_from_visits

import numpy as np

departures = generate_departures_from_visits(visits = visits,
                                    n_vessels=3,
                                    n_installations=3,
                                    n_days_in_period=7)
departures*1

departure days [1 0 1 0 0 1 0]
initial departures
[[0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0]]
remaining_days [0 0 0 0 0 0 0]
CPU times: user 2.2 ms, sys: 60 µs, total: 2.26 ms
Wall time: 1.91 ms


array([[0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]])

In [3]:
print(departures.any(axis=0)*1)
print(visits.any(axis=0)*1)




[1 0 1 0 0 1 0]
[1 0 1 0 0 1 0]
True


In [4]:
list(range(3)

SyntaxError: incomplete input (1784273254.py, line 1)

In [47]:
for i in range(100):
    visits = generate_visits(n_installations = 3,
                        n_days= 7,
                        required_services=np.array([1, 2, 3], dtype=np.int8),
                        )
    print(visits*1)
    departures = generate_departures_from_visits(visits = visits,
                                        n_vessels=3,
                                        n_installations=3,
                                        n_days_in_period=7)
    print(departures*1)
    assert print(np.array_equal(departures.any(axis=0), visits.any(axis=0))), 'generate_departures_from_visits


[[0 0 0 0 1 0 0]
 [0 0 1 0 0 1 0]
 [1 0 1 0 1 0 0]]
departure days [1 0 1 0 1 1 0]
initial departures
[[0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0]]
remaining_days [0 0 0 0 1 0 0]
[[0 0 1 0 1 0 0]
 [0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0]]
True
