In [1]:
import numpy as np

# Test set

In [1]:
%%time

import numpy as np

from psvpp_solver.utils import generate_visits

visits = generate_visits(n_installations = 3,
                    n_days= 7,
                    required_services=np.array([1, 2, 3], dtype=np.int8),
                    )
print(visits*1)

[[0 0 1 0 0 0 0]
 [0 1 0 0 1 0 0]
 [0 1 0 0 1 0 1]]
CPU times: user 222 ms, sys: 169 ms, total: 391 ms
Wall time: 208 ms


In [2]:
# Test generate_departures_from_visits
from psvpp_solver.utils import generate_departures_from_visits

import numpy as np

generate_departures_from_visits(visits = visits,
                                    n_vessels=2,
                                    n_installations=3,
                                    n_days_in_period=7)

IndexError: boolean index did not match indexed array along dimension 1; dimension is 7 but corresponding boolean dimension is 5

In [14]:
departure_days = visits.any(axis=0)

In [20]:
departure_days*1

array([1, 0, 0, 1, 1, 1, 0])

In [23]:
np.delete(departure_days, [6, 1])*1

array([1, 0, 1, 1, 1])

In [38]:
departure_days_idx = np.where(np.array([0,0]))[0]
len(departure_days_idx)

0

In [42]:
a = np.zeros((2,7), dtype=bool)
a[(0, 1, 1, 0), (1, 3, 4, 6)] = 1
a

array([[False,  True, False, False, False, False,  True],
       [False, False, False,  True,  True, False, False]])

In [49]:
np.random.choice(range(3), size=3, replace=False)

array([2, 0, 1])

In [28]:
n_vessels = 3

In [36]:
np.random.choice(departure_days_idx, size=n_vessels, replace=True)

array([3, 3, 5])

In [4]:
import numpy as np
np.random.choice(range(2), size=5, replace=True)

array([0, 0, 0, 0, 0])

In [11]:
7//3

2

## TODO: Unit test:

In [17]:
# Check all vessels selected
np.array_equal(np.unique(assignment), np.arange(3))

True

In [18]:
# Check departure pattern feasible
from psvpp_solver.constraints import check_departures_sufficiently_spread

check_departures_sufficiently_spread(visits=visits,
                                         days_in_period=7,
                                         required_services=np.array([2, 3, 2, 2, 2, 2], dtype=np.int8)
                                         )

False

In [19]:
%%time
# Check departure pattern feasible
from psvpp_solver.constraints import check_departures_sufficiently_spread


while True:
    visits = generate_visits(n_installations=4,
                    n_days=7,
                    days=np.arange(7),
                    service_frequencies=np.array([2, 3, 2, 2, 2, 2], dtype=np.int8),
                    )
    sufficiently_spread = check_departures_sufficiently_spread(visits=visits,
                                         days_in_period=7,
                                         required_services=np.array([2, 3, 2, 2, 2, 2], dtype=np.int8)
                                         )
    if sufficiently_spread:
        break

CPU times: user 12 ms, sys: 62 µs, total: 12 ms
Wall time: 11 ms


In [20]:
visits*1

array([[1, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0]])

In [21]:
# Check that max vessels prepared at installation constraint is satisfied

In [22]:
np.arange(3)

array([0, 1, 2])

In [23]:
idx = rng.choice(np.arange(len(visit_days)), replace=False, size = 3)

idx

array([0, 1, 3])

In [24]:
visit_days[idx]

array([0, 1, 5])