In [5]:
import numpy as np
from psvpp_solver.utils import generate_routes_from_visits_and_departures
from psvpp_solver.utils import generate_visits, generate_departures_from_visits, generate_departures_from_routes, generate_visits_from_routes

In [6]:
n_days_in_period=7

In [2]:
visits = generate_visits(n_installations = 4,
                    n_days_in_period=n_days_in_period,
                    required_services=np.array([2, 3, 2, 2], dtype=np.int8),
                    max_vessels_prepared=2)
visits*1

array([[0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1]])

In [3]:
departures = generate_departures_from_visits(visits=visits,
                                    n_vessels=2,
                                    n_installations=4,
                                    n_days_in_period=7)
departures*1

array([[0, 1, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 0, 0]])

In [8]:
routes = generate_routes_from_visits_and_departures(visits=visits,
                                               departures=departures,
                                               n_days_in_period=7)
routes

array([[[0, 0, 0, 0],
        [3, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [1, 3, 0, 0],
        [2, 4, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [1, 2, 0, 0],
        [4, 0, 0, 0],
        [2, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int8)

In [10]:
generate_visits_from_routes(routes=routes,
                                n_installations=len(visits),
                                n_days_in_period=n_days_in_period)*1


array([[False, False,  True, False, False,  True, False],
       [False, False,  True, False,  True, False,  True],
       [False,  True, False, False, False,  True, False],
       [False, False, False,  True, False, False,  True]])

In [12]:
np.array_equal(visits, generate_visits_from_routes(routes=routes,
                                n_installations=len(visits),
                                n_days_in_period=n_days_in_period))

True

In [14]:
np.array_equal(departures, generate_departures_from_routes(routes=routes))

True